### ISSUE TITLE
`useFileScopedNamespace` does not work

### ISSUE THREAD

**Issue by lonix1** [KreativJos/csharpextensions#103]
I set `"csharpextensions.useFileScopedNamespace": true`.

But a class is still generated like this:

````cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyProject                                  // <---
{                                                    // <---
    public class Blorp
    {
        
    }
}
````

Instead of this:
````cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyProject;

public class Blorp
{
        
}
````

**Context**
extension 1.7.0
vscode 1.69.2

**Comment by bard83** [comment]
Tested locally with the same configuration and works.

Anyway I've experienced once in the past and I've solved unistalling and then reinstalling the extension.

Let us know if it works.

**Comment by lonix1** [comment]
Thanks.

Just tried it again
- In the root of a simple project, it works
- In a monorepo with multiple projects, it fails - it renders `namespace Foo { }` instead of `namespace Foo;`

**Comment by lonix1** [comment]
My workspace is quite complex, but it's something like this:
````
workspace root
  src
    Organisation1
      Foo
        Foo.csproj
      Foo.Tests
        Foo.Tests,csproj
    Organisation2
      Bar
        Bar.csproj
      Bar.Tests
        Bar.Tests.csproj
````

Right click on project "Foo", New C# Class, ...

It will have the old namespace format `namespace Foo { }` instead of `namespace Foo;`

Hope that helps...

**Comment by bard83** [comment]
Are your projects using .net 6 or greater?

**Comment by lonix1** [comment]
Yes. I also have a `Directory.Build.props`, I've updated the schema above to show its location.

If you can't replicate this, then it's "just me". So feel free to close. Maybe someone else will also have this problem and we can find a way to repro.

**Comment by bard83** [comment]
can you provide the content of you projects file, please?

**Comment by lonix1** [comment]
Hey @bard83 I'm gonna close for now, and let's talk about this again if someone else has the same problem?

I feel like I've wasted too much of your time... :smile:

Thanks for your help!
