### ISSUE TITLE
Generate API Controller with version 1.7.0

### ISSUE THREAD

**Issue by MichaelGustavsson** [KreativJos/csharpextensions#104]
**Describe the bug**
When using the extension and right clicking to create an api controller instead of inheriting from ControllerBase it inherits from Controller class. Which is the controller class for MVC controllers with views.

**Context**
- 1.7.0
- VS Code 1.71.0-insider
- MacOS Monterey

**Expected behavior**
I expect that I will have an api controller that inherits from ControllerBase. Like in the previous versions including and prior to version 1.6.0

**Screenshots**

**Comment by KreativJos** [comment]
This was already fixed, but not yet published. I have published a new version containing the fix (published to vscode marketplace & open vsx):
https://github.com/KreativJos/csharpextensions/releases/tag/v1.7.1
