### ISSUE TITLE
Incorrect using statement when creating new XUnit Test?

### ISSUE THREAD

**Issue by Myrnedraith** [KreativJos/csharpextensions#108]
**Describe the bug**
Creating new XUnit Test adds `using XUnit`; from what I can tell, the correct import is `using Xunit`.

**Context**
- Extension: v1.7.1
- VS Code: v1.70.0
- OS: Windows 10

**Expected behavior**
Using statement imports functional package name.

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/18221225/188950874-f90685e3-7282-4078-a7e7-fe5378f576d4.png)
Expected:
![image](https://user-images.githubusercontent.com/18221225/188950720-dc3d094a-ad2c-415f-912f-be37d71706cd.png)

**Comment by KreativJos** [comment]
Fixed & published
