### ISSUE TITLE
New Record template

### ISSUE THREAD

**Issue by heggi** [KreativJos/csharpextensions#112]
We should probably support also this template.

Expected new menu item in C# menu:

|New C#|
- > | Record template |

**Comment by JGMelon22** [comment]
Yeah, would be pretty useful. It's quite tedious need to use the class template and adapt it +1

**Comment by thefish2191** [comment]
I created an extension that can use custom templates, so you guys don't have to request new templates.
I also added modern C# and legacy C#
https://marketplace.visualstudio.com/items?itemName=TheFish2191.add-items

**Comment by bard83** [comment]
Record template is there. Don't know when it will be published.

**Comment by JGMelon22** [comment]
> Record template is there. Don't know when it will be published.

Maybe when .NET 8 releases? Would make sense along side with new features such as primary constructors...

**Comment by bard83** [comment]
this feature is out in [1.8.0](https://marketplace.visualstudio.com/items?itemName=bard83.csharpextension)
