### ISSUE TITLE
Support user-defined templates

### ISSUE THREAD

**Issue by heggi** [KreativJos/csharpextensions#113]
Often I need to create classes with the same bolderplate code.
Now I use `New C#` -> `class`, then replace `public class...` with one of user-defined snippets. Then I need to add some usings.
Ideal would be to add the ability to define your own templates, which will contain all the necessary usings and other bolderplate code

**Comment by thefish2191** [comment]
Hey, I'm working on something exactly like this, I hope I don't bother the orinal author of this repo

You may want to read this https://github.com/thefish2191/CSharp-Stuff/blob/UserDefinedItems/CustomSnippetGuide.md

**Comment by bard83** [comment]
I've actually published a new version [1.8.x](https://marketplace.visualstudio.com/items?itemName=bard83.csharpextension) is out.
It would be interesting to go deep with this feature.

**Comment by bard83** [comment]
closed by https://github.com/bard83/csharpextensions/issues/9
