### ISSUE TITLE
Not able toacces C# for visual studio code (poweredby Omni sharp)

### ISSUE THREAD

**Issue by Amruta2017** [KreativJos/csharpextensions#127]
Type: <b>Feature Request</b>

Not able toacces C# for visual studio code (poweredby Omni sharp)

Extension version: 1.7.3
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by bard83** [comment]
Not clear what's the feature request here? 
Can you please share more details or logs?

the [1.8.0](https://marketplace.visualstudio.com/items?itemName=bard83.csharpextension) is out there.
