### ISSUE TITLE
omnisharp

### ISSUE THREAD

**Issue by Abiousnuel** [KreativJos/csharpextensions#128]
Type: <b>Feature Request</b>

it is saying it cannot recognise the command 'o.restart'

Extension version: 1.7.3
VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by bard83** [comment]
Not clear what's the feature request here?
Can you please share more details or logs?

the [1.9.0](https://marketplace.visualstudio.com/items?itemName=bard83.csharpextension) is out there, it would be nice if you can try with it.
