### ISSUE TITLE
remove the initial "using".

### ISSUE THREAD

**Issue by v-hung** [KreativJos/csharpextensions#129]
newly created C# class will "using" many things

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
```

I removed it and just left the namespace and class alone. Please show me the way

**Comment by bard83** [comment]
Hi,
there is a specific setting that you should opt-out.
Please go in the extensions settings -> C# Extensions -> untick **Usings: Include**

![immagine](https://github.com/KreativJos/csharpextensions/assets/11898472/c34ebd31-b861-4d69-96de-f7f5d7c2a97f)

If you landed on this repo, your extension version is an older one. This extension has been republished. [Here](https://marketplace.visualstudio.com/items?itemName=bard83.csharpextension) the newer version.
