### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by KreativJos** [KreativJos/csharpextensions#23]
Hi all!

The past 6 months have been a bit busy in my life, and I am not the best in communicating these things.
I have tried to review a few pull-requests, but I cannot get the vscode test platform running in a correct way since Oktober 2020.

If someone knows enough about nodejs and vscode extensions to review pull-requests, I'd gladly give them access to do so.

**Comment by PoLaKoSz** [comment]
Hi!

Thank You for the access.
I'm sad, but I won't be too active because I'm "forced" to use VS 2019  instead of VS Code at least until [the Omisharp devs](https://github.com/OmniSharp/omnisharp-vscode/issues/1794) fix this 4 years old issue.

**Comment by KreativJos** [comment]
You're the only one who is at least a bit active here, so I'd be glad if you'd help out with pull-request reviewing!
The issue you are referencing is a bit annoying to me too. I only use Visual Studio to run tests or a code generator here and there.

**Comment by bard83** [comment]
In case of cooperation what's needed?
- node and typescript
- vs code extension knowledge

something else?

**Comment by KreativJos** [comment]
The main issues are, in order:

1.  Currently I'm the only one semi-actively involved in this extension, and I do not have much spare time (a few hours a month);
2. There is no-one to review PRs that I have made, so stupid errors creep into the code;
3. Issues depend on me personally for communication & handling;
4. Unit tests should be created, but I don't have the time and knowledge;
5. Some processes should be put into place, like:
    1. auto-publishing,
    2. auto-checking PRs (eslint / unit tests),

**Comment by bard83** [comment]
Glad to help.

**Comment by KreativJos** [comment]
Thank you. You have been invited.
