### ISSUE TITLE
.csproj default namespace setting support.

### ISSUE THREAD

**Issue by es-repo** [KreativJos/csharpextensions#3]
`.csproj` file allows to specify default namespace. For example:

`<RootNamespace>My.Namespace</RootNamespace>`

When it's specified then Visual Studio (not Code) will use this namespace when new class or interface is created. Would be nice if  `csharpextensions` will support this setting as well.

**Comment by KreativJos** [comment]
If you'd make a pull-request to solve this, I'd be happy to merge and publish.
You would probably want to start around this line: https://github.com/KreativJos/csharpextensions/blob/master/src/extension.ts#L52

**Comment by PoLaKoSz** [comment]
Didn't tested it, but here is an implementation from @AvinFernando:
https://github.com/AvinFernando/csharpextensions/commits/RootNamespace

**Comment by PoLaKoSz** [comment]
I would like to implement this for (including to support legacy `project.json` too).

**Comment by KreativJos** [comment]
You're welcome to.
I have tried a simple merge, but the code is a bit unorganized on both sides. I don't have the time to implement this myself.

**Comment by PoLaKoSz** [comment]
Thank You! Is it ok to implement the featur with classes? I will test them with mocha tests too.

**Comment by KreativJos** [comment]
Fine by me.
