### ISSUE TITLE
Feature: copy file to output directory

### ISSUE THREAD

**Issue by marcusturewicz** [KreativJos/csharpextensions#4]
Working with .NET, sometimes you want to copy a certain file, or files, to the output directory so they can be read or used at runtime. This is particularly useful in unit tests or for runtime assets etc.

This is typically done by adding the following code to the project file:

```xml
  <ItemGroup>
    <None Update="file.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

In Visual Studio, this can be easily added with the properties dialog, as here https://stackoverflow.com/a/10828462/6939988.

But, I always forget this syntax and have to look it up [on StackOverflow](https://stackoverflow.com/questions/44374074/copy-files-to-output-directory-using-csproj-dotnetcore) everytime.

Therefore, it would be nice if this extension provided a simple menu item that is available upon right-clicking on a file in the workspace i.e. "Copy to output directory" which has another list to select "Always", "PreserveNewest" or "Never", and clicking it adds the relevant code (like above) to the project file.

Happy to do the PR for this if you think it adds value/makes sense for this extension.

**Comment by KreativJos** [comment]
It seems to me that one would expect a whole set of csproj commands, if such a command would be included. That does not sound like a bad idea, but it might be better to include it in one of these extensions:
https://marketplace.visualstudio.com/items?itemName=jRichardeau.vscode-vsproj
https://marketplace.visualstudio.com/items?itemName=lucasazzola.vscode-csproj

**Comment by marcusturewicz** [comment]
I haven't come across those extensions before, thanks. The second one looks like the right place for this feature. Cheers!
