### ISSUE TITLE
namespace becomes a dot 

### ISSUE THREAD

**Issue by EricZX26** [KreativJos/csharpextensions#5]
Hi KreativJos,

Thanks for updating this lovely extension.
I encountered a problem where the namespace becomes a dot when the class name is the same or begins with the project name.
Could you please take a look at this issue?
[https://www.youtube.com/watch?v=ciikZLQM2hk](url)

Thanks and Regards

**Comment by brunohenriquepj** [comment]
Hi @KreativJos, I fix this issue on pull request #6, can you check the change? Any change or doubt, I am available.

**Comment by KreativJos** [comment]
Merged & updated.
It is currently in the verification process.

**Comment by KreativJos** [comment]
Seems to be working now.
