### ISSUE TITLE
Automate build / release

### ISSUE THREAD

**Issue by KreativJos** [KreativJos/csharpextensions#55]
- [ ] Use github for building
- [ ] Auto increment version
- [ ] Auto-update changelog
- [ ] Publish to vscodium marketplace
- [ ] Publish to vscode marketplace
- [ ] Disable user push to master, except from PR

**Comment by bard83** [comment]
> Auto increment version

I see it non trivial.
How could the pipeline realizes when bump the version as major or minor?

**Comment by bard83** [comment]
>  Auto-update changelog
>  Publish to vscodium marketplace
>  Publish to vscode marketplace

The `Auto-update changelog` should be meant slightly different. When a tag is created the assumption is that a draft release is opened and the changelog gets created. Open question. What should be inside the changelog a list of the commit messages?

These `Publish to vscodium marketplace` and `Publish to vscode marketplace` are done when a release is created (release loses the draft state).
