### ISSUE TITLE
Razor Page format error

### ISSUE THREAD

**Issue by mihaluo** [KreativJos/csharpextensions#57]
in the `cshtmlTemplate.ts `
const cshtmlFilePath = `${pathWithoutExtension}.xaml`;
const csFilePath = `${pathWithoutExtension}.xaml.cs`;
Causes a razor file format problem to be created

**Comment by KreativJos** [comment]
Wow, that is a stupid mistake... Should be .cshtml & .cshtml.cs for sure.
