### ISSUE TITLE
Maintain End of Line/File for new class/interface/enum etc.

### ISSUE THREAD

**Issue by bard83** [KreativJos/csharpextensions#67]
When a new C# element (class/interface/enum etc...) is created, the end of line/file is always set to CRLF. It would be nice whether the new element maintains what currently is set globally for the IDE (in my case LF).

**Comment by KreativJos** [comment]
You are referencing vscode setting `files.eol`? I have applied that setting in the template-writing, so new files should respect that setting.
I don't know when I'll publish, but I'll let you know.
