### ISSUE TITLE
new C# Test Class

### ISSUE THREAD

**Issue by bard83** [KreativJos/csharpextensions#71]
It would be nice to have a new menu item in 'New C# -> Test Class` when a folder in a test project is selected. 
The test class should be comply to the test framework used.

**Comment by KreativJos** [comment]
Seems to be a simple addition, which can be added fairly easily.

TODO:

1. Which types of test classes are there, and which do we want to support?
2. Do we want to choose the type of test, or do we want the user to?
    1. If we want to choose, how would we know which type of test the user wants? - Based on `PackageReference`-s? But what if more than one is applied?

**Comment by bard83** [comment]
> Do we want to choose the type of test, or do we want the user to?
>   i. If we want to choose, how would we know which type of test the user wants? - Based on PackageReference-s? But what if more than one is applied?

My opinion. We choose and in case of multiple references are applied then let the user choose. When the user chooses, a sub menu item with the available options could be shown. `New C# -> Test Class -> i. xunit ii. nunit ... etc`

**Comment by KreativJos** [comment]
> > Do we want to choose the type of test, or do we want the user to?
> > i. If we want to choose, how would we know which type of test the user wants? - Based on PackageReference-s? But what if more than one is applied?
> 
> My opinion. We choose and in case of multiple references are applied then let the user choose. When the user chooses, a sub menu item with the available options (based on the references) could be shown. `New C# -> Test Class -> i. xunit ii. nunit ... etc`

That would mean creating a more complex menu structure (submenus of submenus are supported now, so it is a possibility) and implementing a custom `where` clause (for which I don't know if this idea can be implemented): https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context

**Comment by bard83** [comment]
>Which types of test classes are there, and which do we want to support?
>
>   i. [XUnit](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test)
>   ii. [NUnit](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit)
>   ii. [MSTest](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest)

I'd say yes. 

> That would mean creating a more complex menu structure (submenus of submenus are supported now, so it is a possibility) and implementing a custom where clause (for which I don't know if this idea can be implemented): https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context

To keep things easier then the menu should provide the items based on the reference/s. Which means:
-  in case only 1 is used (e.g XUnit):
```
New C# ->  
                   | XUnit Class  |
```
- in case of multiple are used (e. g. XUnit, NUnit):
```
New C# -> 
                   | XUnit Class  |
                   | NUnit Class  |
```

**Comment by KreativJos** [comment]
I'm thinking this should be split into 2 parts:

1. Unit test templates
2. Add when-clause to specific templates (xaml, unit tests, views etc)

**Comment by bard83** [comment]
Just to understand better. What's the benefit of this splitting?

**Comment by KreativJos** [comment]
The when-clause is a separate feature, because it should be applied across the board:
Xaml should only be available in wpf projects
Controllers only in Asp projects
etc

The unit test templates can simply be added as templates with their respective commands.
