### ISSUE TITLE
Adding Class, Interface, Controller, ... should use PascalCase by default

### ISSUE THREAD

**Issue by doggy8088** [KreativJos/csharpextensions#76]
In C#, when creating Class, Interface, Controller, Api Controller, most of the case should use PascalCase as a default.

For now, the C# extension use all lower-case by default as a hint. I think this can be changed.

![image](https://user-images.githubusercontent.com/88981/162660474-28d13be5-7215-4903-8f9e-71eab05acd42.png)

**Comment by KreativJos** [comment]
Personally, I don't really care about that, because I always change the preset value.
If someone would provide a PR for this, I'd be happy to merge.

**Comment by doggy8088** [comment]
@KreativJos PR created.
