### ISSUE TITLE
 Error creating new .cs files on Linux

### ISSUE THREAD

**Issue by PauloZier** [KreativJos/csharpextensions#83]
After the update, the extension is giving an error when trying to create a new .cs file.
I'm using Linux [Debian 11]

**Comment by KreativJos** [comment]
Can you post a screenshot of the error given, or the content of it?
And, if possible, include the extension host logging, which can be found here:
![image](https://user-images.githubusercontent.com/20839414/164190217-1f4f3d40-068f-4f3f-bd70-c7b40adde39a.png)

**Comment by PauloZier** [comment]
![image](https://user-images.githubusercontent.com/40168996/164221722-f7f2444b-0bf6-467c-96b2-73694a388e02.png)
![image](https://user-images.githubusercontent.com/40168996/164221996-14b478b9-4b4e-40e7-8ab7-977a53586a73.png)

**Comment by KreativJos** [comment]
The issue is in the casing of the file path, caused by this issue: #76 and PR #77 
I'll try to make a fix and unit test for this, maybe with better error handling.

**Comment by PauloZier** [comment]
Thank you very much! To temporarily solve it I reverted to the previous version.

**Comment by KreativJos** [comment]
Unit tests aren't easily possible, because of #84 
I have fixed the issue, and tested it in WSL

**Comment by BrandonAvantGMS** [comment]
@KreativJos , is there an ETA on a release for this fix?

**Comment by BrandonAvantGMS** [comment]
> Thank you very much! To temporarily solve it I reverted to the previous version.

Is there a trick that I'm missing for installing an older version in WSL? When I hit "Install in WSL", it's installing the most recent version (i.e. v1.6.2) regardless of me picking 1.6.1 or 1.6.0.

**Comment by PauloZier** [comment]
![image](https://user-images.githubusercontent.com/40168996/164534511-45f270c6-2be6-4200-a5dd-e15535146b44.png)

@BrandonAvantGMS , I don't know how it works in WSL, but in VS Code I did it this way

**Comment by KreativJos** [comment]
> @KreativJos , is there an ETA on a release for this fix?

The PR has to be checked by someone else, so it depends on whether they have the time.
If it is accepted, a new release will be created.

**Comment by KreativJos** [comment]
> ![image](https://user-images.githubusercontent.com/40168996/164534921-3fc69830-5aa0-4cf9-8df5-b3b646bc7487.png)
> 
> @BrandonAvantGMS , I don't know how it works in WSL, but in VS Code I did it this way

It is the same in WSL (mine isn't selectable as I installed the vsix file from my own build):
![image](https://user-images.githubusercontent.com/20839414/164626538-b1e126d5-aba2-4918-a260-6680f864bd2b.png)
