### ISSUE TITLE
Project name disappears in namespace when creating new *.cs file

### ISSUE THREAD

**Issue by d0972058277** [KreativJos/csharpextensions#86]
![CleanShot 2022-04-21 at 14 35 52](https://user-images.githubusercontent.com/17632773/164389479-89640b8b-6512-4d81-894d-8675264eebb3.png)

**Comment by KreativJos** [comment]
Could you provide some context?

1. The version of the extension
2. The folder structure from the csproj to the created file
3. The csproj TargetFramework & optional RootNamespace
4. Your OS (Mac / Windows / Linux)

**Comment by d0972058277** [comment]
> Could you provide some context?
> 
> 1. The version of the extension
> 2. The folder structure from the csproj to the created file
> 3. The csproj TargetFramework & optional RootNamespace
> 4. Your OS (Mac / Windows / Linux)

The version of the vs code:
v1.66.2

The version of the extension:
v1.6.2

The folder structure & csproj TargetFramework:
ServiceCluster-Notification
└ charts
└ src
  └ NotificationSystem.Domain
    └ (NotificationSystem.Domain.csproj) netstandard2.0
  └ NotificationSystem.Application
    └ (NotificationSystem.Application.csproj) netstandard2.0
└ test
  └ NotificationSystem.UseCase.Test
  	└ (NotificationSystem.UseCase.Test.csproj) netcoreapp3.1
    └ Aggregates
	└ Commands
	└ DomainEventHandlers
	└ IntegrationEvents
	
My OS:
Apple M1 Max
macOS Monterey 12.2.1


It was working fine yesterday, but today I found the problem.
Now using jchannon's C# Extensions v1.3.1 does not have this problem.

**Comment by KreativJos** [comment]
Fixed & released in version 1.6.3
