### ISSUE TITLE
Namespace name generated from one level up

### ISSUE THREAD

**Issue by abaula** [KreativJos/csharpextensions#88]
"This extension traverses up the folder tree to find the project.json or *.csproj and uses that as the parent folder to determine namespaces."

Seems it doesn't work anymore.

**Comment by KreativJos** [comment]
It does for me:
![image](https://user-images.githubusercontent.com/20839414/164714976-8ae8d05b-81bd-46f7-b5b7-9353265824e3.png)

Could you provide some context:

1. The version of the extension
2. The folder structure from the csproj to the created file
3. The csproj TargetFramework & optional RootNamespace
4. Your OS (Mac / Windows / Linux)

**Comment by luciano-souza** [comment]
Having same issue
![image](https://user-images.githubusercontent.com/41630391/164729768-32d03e06-a135-4065-bdd5-0c6eb242ef74.png)
![image](https://user-images.githubusercontent.com/41630391/164729986-397d0aac-a8c1-4e9c-a496-44b5354ac259.png)
![image](https://user-images.githubusercontent.com/41630391/164730061-d1dc43a4-ac8d-4e5a-9416-b5e8ffd07b3c.png)


1. The version of the extension => 1.6.2
2. The folder structure from the csproj to the created file => image above
3. The csproj TargetFramework & optional RootNamespace => I dont know if the images show what you want here
4. Your OS (Mac / Windows / Linux) => Windows

**Comment by KreativJos** [comment]
> 

The issue can be replicated by having this same structure. I'll try to find out why.

**Comment by KreativJos** [comment]
Fixed and released with 1.6.3
