### ISSUE TITLE
Unable to use the extension on vscode under linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by frstonge** [KreativJos/csharpextensions#94]
Hi,

First, I am using vscode in linux (Ubuntu 20.04)  The extension does not work anymore. When I try to create any kind of file (class, interface, etc), I get an error message:
Errot trying to create file '/pathtofile/file' from template '/pathtotemplate/template.tmpl'
The original extension from jchannon still works.
Thanks!

**Comment by KreativJos** [comment]
Probably a duplicate of #83 which is fixed in the just released version 1.6.3
Can you try if the current version fixes your issue?

**Comment by bard83** [comment]
@frstonge can you confirm that you were using 'v1.6.2'?

**Comment by frstonge** [comment]
Hi,
This is resolved using 1.6.3! I can't confirm I was using 1.6.2, but I guess I was, because I was just installing the latest version.
This works now, thanks!
